version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - gradle-project

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew build
